### ISSUE TITLE
Invitations: also create users (via magic link) 

### ISSUE THREAD

**Issue by awoimbee** [p2-inc/phasetwo-admin-portal#136]
There was a recent discussion about creating users along with sending invitations in https://github.com/p2-inc/keycloak-orgs/issues/168.
The proposed (and documented) work-around seems great: https://github.com/p2-inc/phasetwo-docs/blob/0960641a5b3050dbf140464896aa4f0933eb7ac2/docs/organizations/invitations.md#magic-link

It seems to me like this interface should always send a magic link, with either:
* give the option to create a user if it doesn't exist (with a checkbox)
* always create a user

**Comment by xgp** [comment]
I like the idea, but I'm generally opposed to depending on other extensions.

I'd prefer a specific function in the resource and an action token/handler for invitations, rather than the workaround. That could work similar to the magic link, but constrain the functionality to just accepting the invitation and creating a user if they don't exist. 

If you want to PR that, please put it in `keycloak-orgs`.
