### ISSUE TITLE
wrong url of css and scripts when opening portal

### ISSUE THREAD

**Issue by paulwer** [p2-inc/phasetwo-admin-portal#87]
when opening the admin-portal at: https://phase-two-instance.com/realms/master/portal/
the resources are fetched from:
```
<script defer="defer" src="/auth/realms/master/portal/static/js/main.a5619124.js"></script>
<link href="/auth/realms/master/portal/static/css/main.2f5be0a3.css" rel="stylesheet">
```

the right url would be: (without /auth, checked the urls and they serve files)
```
<script defer="defer" src="/realms/master/portal/static/js/main.a5619124.js"></script>
<link href="/realms/master/portal/static/css/main.2f5be0a3.css" rel="stylesheet">
```

have I did something wrong within my configuration or is this a bug?

an other header is:
```
<base href="/auth/realms/master/portal/"/>
```

**Comment by paulwer** [comment]
old keycloak instances has used the /auth prefix.
any chances to fix this in the next release?

**Comment by paulwer** [comment]
@xgp is there an upcomming change for us in the pipeline?😊

**Comment by xgp** [comment]
@paulwer Customers are all using `/auth` relative path URL so this is low priority. Feel free to PR the fix.

**Comment by paulwer** [comment]
@xgp i added a simple check, if the pathname includes /auth/ or not, to support old / your versions and newer keycloak versions, when installing from dockerimage

**Comment by xgp** [comment]
Thanks. I merged, and I'll take a look when we release a new public docker image. TBH there's a lot of cases where we assume that `/auth` will be the relative path, as most of our work started before Keycloak removed that necessity. Because of that, our hosted version, and all of our customers use it. I'd like to wave a magic wand and have it fixed everywhere, but I'm afraid it will be a game of whack-a-mole for people that are using no/another relative path.

**Comment by paulwer** [comment]
@xgp i read this at keycloak before. maybe its time to migrate your applications to this new standard also. Or to implement at least the same behavior within the oss docker image.

Shall anyone create an issue / feature request out of this?
